[package]
name = "vrp-api"
version = "0.1.0"
authors = ["Ilya Builuk <ilya.builuk@gmail.com>"]
edition = "2018"

[dependencies]
lambda_http = "0.1.1"
serde = { version = "1.0.106", features = ["derive"] }
