[package]
name = "server"
version = "0.1.0"
authors = ["reinterpretcat <ilya.builuk@gmail.com>"]
edition = "2018"


[dependencies]
common =  { path = "../common" }
vrp-pragmatic = "1.4.2"

actix-web = "3.0.0-beta.3"