[package]
name = "server"
version = "0.1.0"
authors = ["reinterpretcat <ilya.builuk@gmail.com>"]
edition = "2018"


[dependencies]
vrp-cli = "1.5.7"

actix-web = "3.0.0-beta.3"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
env_logger = "0.7"
futures = "0.3"
